seed: 1
output_prefix: /fs/cbcb-scratch/jfan03/treeterm-paper

replicates: [1,2,3,4,5,6]
fc_min: 1.4
fc_max: 2.8
frag_len: 200
lib_size: 40_000_000
gc_bias: true
txp_fasta: data/gencode.v26.annotations.short.names.fa
txdb: data/gencode.v26.annotation.sqlite
cortex_tpms: frontal_cortex.tsv.gz
meandisp: meanDispPairs/meanDispPairs.rda
gc_params: data/fitpar_all.rda

sal_path: "/fs/cbcb-lab/rob/students/noor/Uncertainity/treeTerminusScripts/Chimpanzee/no_thresh_boot/.snakemake/conda/b5dc9e9ebd55a53225f40312a659f7a2/bin/salmon"
sal_idx_path: "/fs/cbcb-lab/rob/students/noor/Uncertainity/brain_sim/annotation/sal_ind_nodup"
posterior_type: gibbs #specific type of posterior sampling gibbs or bootstrap
nreplicates: 100 # posterior samples
thinning_factor: 100

term_path: "/fs/cbcb-lab/rob/students/noor/Uncertainity/terminus/target/release/terminus"
treeterm_path: "/fs/cbcb-lab/rob/students/noor/Uncertainity/TreeTerminus/target/release/treeterminus"
